// ObjectIDs are generated by MongoDB driver and are used to uniquely identify a
// document. They consist of 12 bytes:
//     - 4 bytes: timestamp
//     - 3 bytes: machine identifier
//     - 2 bytes: process identifier
//     - 3 byes: counter
// ObjectIDs are almost unique. In theory, there is a chance for two ObjectIDs to be
// equal but the odds are very low (1/16,000,000) for most real-world applications.

const mongoose = require("mongoose");

const id = mongoose.Types.ObjectId();

console.log(id);
console.log(id.getTimestamp());

const isValid = mongoose.Types.ObjectId.isValid("1234");
console.log(isValid);
